version: '3.9'

services:
  app_django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn firstsite.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    volumes:
      - ./firstsite/database:/app_django/database
    extra_hosts:
      - "host.docker.internal:host-gateway"