FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /app_django

RUN pip install --upgrade pip 'poetry==2.2.1'
RUN poetry config virtualenvs.create false --local
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

COPY firstsite .

CMD ['gunicorn', 'firstsite.wsgi:application', '--bind', '0.0.0.0:8000']